apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: consul-client
  labels:
    app: consul-client
spec:
  selector:
    matchLabels:
      name: consul-client
  template:
    metadata:
      labels:
        name: consul-client
    spec:
      containers:
      - name: consul-client
        image: consul:1.4.0
        env:
          - name: GOSSIP_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: consul-secrets
                key: gossip-encryption-key
        command: ["/bin/sh", "-c"]
        args:
          - |
              exec /bin/consul agent \
              -join=consul \
              -retry-join=consul \
              -bind=0.0.0.0 \
              -client=0.0.0.0 \
              -data-dir=/consul/data \
              -hcl="ports { grpc = 8400 }" \
              -encrypt ${GOSSIP_ENCRYPTION_KEY}
        ports:
          - name: http
            containerPort: 8500
            hostPort: 8500
          - name: rpc
            containerPort: 8400
            hostPort: 8400
          - name: serflan-tcp
            containerPort: 8301
            protocol: "TCP"
          - name: serflan-udp
            containerPort: 8301
            protocol: "UDP"
          - name: serfwan-tcp
            containerPort: 8302
            protocol: "TCP"
          - name: serfwan-udp
            containerPort: 8302
            protocol: "UDP"
          - name: server
            containerPort: 8300
          - name: consuldns-tcp
            containerPort: 8600
            protocol: "TCP"
          - name: consuldns-udp
            containerPort: 8600
            protocol: "UDP"
        volumeMounts:
          - name: data
            mountPath: /consul/data
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
